import "./globals.css";

import { Footer } from "@/components/global/footer";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { Navbar } from "@/components/global/navbar";
import { Provider } from "@/components/providers/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html
            lang="en"
            className={`${inter.className} scroll-smooth antialiased`}
        >
            <body>
                <Provider>
                    <Navbar />
                    <main className="flex flex-col items-center justify-between p-20">
                        {children}
                    </main>
                    <Footer />{" "}
                </Provider>
            </body>
        </html>
    );
}
